### ISSUE TITLE
python310@3.10.8: decompress error

### ISSUE THREAD

**Issue by arrrgi** [ScoopInstaller/Versions#713]
### Scoop Configuration

```json
{
  "global_path": "C:\\ProgramData\\scoop",
  "last_update": "2022-10-18T13:05:42.4676578+11:00",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}
```

### Output from dark.log

```
setup.exe
dark.exe : error DARK0001 : Access to the path 'C:\Users\REDACTED\scoop\apps\python310\3.10.8\_tmp\AttachedContainer\exe.msi' is denied.

Exception Type: System.UnauthorizedAccessException

Stack Trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Microsoft.Tools.WindowsInstallerXml.BurnReader.ExtractAttachedContainer(String outputDirectory, String tempDirectory)
   at Microsoft.Tools.WindowsInstallerXml.Unbinder.UnbindBundle(String bundleFile, String exportBasePath)
   at Microsoft.Tools.WindowsInstallerXml.Unbinder.Unbind(String file, OutputType outputType, String exportBasePath)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Dark.Run(String[] args)
```

### Environment details

**Operating system:** Windows 2016 Standard
**Version:** 10.0.14393 Build 14393

### Notes

Attempted to install in from both an unelevated and elevated command prompt, both resulting with the same error detail

**Comment by arrrgi** [comment]
Whilst not entirely specific to this error, some searching across other issues with decompressing app packages points to newest an issue in versions of 7zip newer than version 19.00.

I uninstalled the 7zip package which I had installed globally, then installed 7zip19.00-helper, after which I was able to successfully install the Python version I was after.
